### PR TITLE
Flipped `incompatible_disallow_empty_glob`

### PR DESCRIPTION
**Pull request by abrisco**
For this change I assumed there was a reason these sources were not passed directly vs being in a glob and opted to simply allow files to be missing.

### CODE REVIEW

**Comment by abrisco** [comment]
Windows and MacOS targets are failing due to https://github.com/jmillikin/rules_bison/issues/15. I opted not to try to fix that in this change since I wasn't confident that I'd not impacted existing behavior. Hopefully this doesn't block merging and the linking issues can be discussed on the new Github issue.

**Comment by abrisco** [comment]
@jmillikin despite the failed builds (see https://github.com/jmillikin/rules_bison/pull/14#issuecomment-2263768637) I think this is ready to review 🙏

**Comment by abrisco** [comment]
For those waiting for this to land, a patch file can be downloaded here: [@rules_hdl//dependency_support/org_gnu_bison/bison_empty_glob.patch](https://github.com/hdl/bazel_rules_hdl/blob/acf12a967d84db546c6595fbf232b3406c3a15f4/dependency_support/org_gnu_bison/bison_empty_glob.patch)

**Comment by jmillikin** [comment]
Thanks for the patch and bug report!

This PR's commit log seems to have picked up some stray files from your working directory, so I pushed these two commits instead:
* https://github.com/jmillikin/rules_bison/commit/ae8dd16bcbc0abb6c97c744eaa2007b2fc6b123e sets `allow_glob`
* https://github.com/jmillikin/rules_bison/commit/352bf2c1c0366ff69cc43bdee7f748de2c480511 adds the Java toolchain dependency.

Is this something you need a release for imminently, or can it wait a week or two for some other fixes to land first?

**Comment by abrisco** [comment]
> Thanks for the patch and bug report!
> 
> 
> 
> This PR's commit log seems to have picked up some stray files from your working directory, so I pushed these two commits instead:
> 
> * https://github.com/jmillikin/rules_bison/commit/ae8dd16bcbc0abb6c97c744eaa2007b2fc6b123e sets `allow_glob`
> 
> * https://github.com/jmillikin/rules_bison/commit/352bf2c1c0366ff69cc43bdee7f748de2c480511 adds the Java toolchain dependency.
> 
> 
> 
> Is this something you need a release for imminently, or can it wait a week or two for some other fixes to land first?

The strays were intentional. The lack of the `.gitignore` risked actual strays and the `.bazelrc` was for regression testing globs. I would definitely recommend taking at least the `.bazelrc` but as long as there is some regression testing for the issue I'm a happy camper!

Thank you for the review and the release is not time critical amd don't mind waiting 😃

**Pull request closed without merging**
